### ISSUE TITLE
execution reverted (unknown custom error)

### ISSUE THREAD

**Issue by samlaf** [axiom-crypto/axiom-quickstart#1]
Getting this error when running `npm start`:
```
/Users/samlaf/devel/zk/axiom-quickstart/node_modules/ethers/src.ts/utils/errors.ts:694
            error = new Error(message);
                    ^
Error: execution reverted (unknown custom error) (action="estimateGas", data="0x96e41fe9", reason=null, transaction={ "data": "0x32c4cda2df6839fce8290844670d51a4bb31b725a8ec9e8ba34e52c2e70968c5722aef20000000000000000000000000bcde0ada340c525630dfd38cd88e7d9d60ad0326000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001b9010000000801008b7f0a02008b7f0a5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f04008b7f0a5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004008b7f0a5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000002008b7f0a8eb3a522cab99ed365e450dad696357de8ab7e9d02008b7f0b8eb3a522cab99ed365e450dad696357de8ab7e9d04008b7f0c8eb3a522cab99ed365e450dad696357de8ab7e9d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000104008b7f0d8eb3a522cab99ed365e450dad696357de8ab7e9d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000", "from": "0xBcDE0AdA340C525630DFd38cD88E7D9d60ad0326", "to": "0x4Fb202140c5319106F15706b1A69E441c9536306" }, invocation=null, revert=null, code=CALL_EXCEPTION, version=6.8.0)
    at makeError (/Users/samlaf/devel/zk/axiom-quickstart/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at getBuiltinCallException (/Users/samlaf/devel/zk/axiom-quickstart/node_modules/ethers/src.ts/abi/abi-coder.ts:118:21)
    at Function.getBuiltinCallException (/Users/samlaf/devel/zk/axiom-quickstart/node_modules/ethers/src.ts/abi/abi-coder.ts:230:16)
    at JsonRpcProvider.getRpcError (/Users/samlaf/devel/zk/axiom-quickstart/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:906:32)
    at /Users/samlaf/devel/zk/axiom-quickstart/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:526:45
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'CALL_EXCEPTION',
  action: 'estimateGas',
  data: '0x96e41fe9',
  reason: null,
  transaction: {
    to: '0x4Fb202140c5319106F15706b1A69E441c9536306',
    data: '0x32c4cda2df6839fce8290844670d51a4bb31b725a8ec9e8ba34e52c2e70968c5722aef20000000000000000000000000bcde0ada340c525630dfd38cd88e7d9d60ad0326000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001b9010000000801008b7f0a02008b7f0a5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f04008b7f0a5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004008b7f0a5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000002008b7f0a8eb3a522cab99ed365e450dad696357de8ab7e9d02008b7f0b8eb3a522cab99ed365e450dad696357de8ab7e9d04008b7f0c8eb3a522cab99ed365e450dad696357de8ab7e9d0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000104008b7f0d8eb3a522cab99ed365e450dad696357de8ab7e9d0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000',
    from: '0xBcDE0AdA340C525630DFd38cD88E7D9d60ad0326'
  },
  invocation: null,
  revert: null,
  shortMessage: 'execution reverted (unknown custom error)',
  info: {
    error: { code: 3, message: 'execution reverted', data: '0x96e41fe9' },
    payload: {
      method: 'eth_estimateGas',
      params: [Array],
      id: 4,
      jsonrpc: '2.0'
    }
  }
}
```

**Comment by samlaf** [comment]
Ah just saw the comment above `currentQueryBlock`:
```
// This must be set to a number that hasn't been queried yet (or any values that would calculate
// a different keccakQueryResposne) since the AxiomV1Query contract saves the keccakQueryResponses
// in a mapping and the call will fail if the keccakQueryResponse already exists in that mapping.
```

Is there anyway to get ts to print the actual error (instead of "unknown custom error")?
Otherwise probably best to catch the error and console.log() the above comment instead of having it hidden in the code. Should also ideally be in the README.
