### ISSUE TITLE
Stucked at the quickstart

### ISSUE THREAD

**Issue by boundless-forest** [axiom-crypto/axiom-quickstart#30]
I tried to figure out how the axiom works and tested following the quickstart tutorial and have two issues yet.

- Forge test error

```sh
$ forge test -vvv
[⠢] Compiling...
No files changed, compilation skipped
2024-03-19T08:56:57.471377Z ERROR cheatcodes: non-empty stderr input=["node", "./lib/axiom-std/build/axiom-std-cli-build.js", "readCircuit", "app/axiom/average.circuit.ts", "https://rpc.sepolia.org"] stderr="node:internal/modules/cjs/loader:1147\n  throw err;\n  ^\n\nError: Cannot find module 'commander'\nRequire stack:\n- /home/bear/coding/airdrop-space/axiom/axiom-quickstart/lib/axiom-std/build/axiom-std-cli-build.js\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)\n    at Module._load (node:internal/modules/cjs/loader:985:27)\n    at Module.require (node:internal/modules/cjs/loader:1235:19)\n    at require (node:internal/modules/helpers:176:18)\n    at Object.<anonymous> (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/lib/axiom-std/build/axiom-std-cli-build.js:297:19)\n    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n    at Module.load (node:internal/modules/cjs/loader:1207:32)\n    at Module._load (node:internal/modules/cjs/loader:1023:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/bear/coding/airdrop-space/axiom/axiom-quickstart/lib/axiom-std/build/axiom-std-cli-build.js'\n  ]\n}\n\nNode.js v21.4.0\n"
2024-03-19T08:56:57.471566Z ERROR forge::runner: setUp failed reason=EvmError: Revert contract=0x90193C961A926261B756D1E5bb255e67ff9498A1

Running 1 test for test/AverageBalance.t.sol:AverageBalanceTest
[FAIL. Reason: setup failed: EvmError: Revert] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 2.57s
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/AverageBalance.t.sol:AverageBalanceTest
[FAIL. Reason: setup failed: EvmError: Revert] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

Using `PROVIDER_URI_SEPOLIA="https://eth-sepolia.api.onfinality.io/public"` as my rpc provider based on the latest version of this repo.

- Failed to send on-chain query

```sh
$ npx tsx app/index.ts 
/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/utils/errors.ts:694
            error = new Error(message);
                    ^


Error: could not coalesce error (error={ "code": -32000, "message": "requested block is too old, block must be within 100000 blocks of the head block number (currently 5516633)" }, payload={ "id": 3, "jsonrpc": "2.0", "method": "eth_getProof", "params": [ "0xeaa455e4291742ec362bc21a8c46e5f2b5ed4701", [  ], "0x4c4b40" ] }, code=UNKNOWN_ERROR, version=6.10.0)
    at makeError (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at JsonRpcProvider.getRpcError (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1049:25)
    at <anonymous> (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: -32000,
    message: 'requested block is too old, block must be within 100000 blocks of the head block number (currently 5516633)'
  },
  payload: {
    method: 'eth_getProof',
    params: [ '0xeaa455e4291742ec362bc21a8c46e5f2b5ed4701', [], '0x4c4b40' ],
    id: 3,
    jsonrpc: '2.0'
  },
  shortMessage: 'could not coalesce error'
}

Node.js v21.4.0

---

$ npx tsx app/index.ts
/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/utils/errors.ts:694
            error = new Error(message);
                    ^


Error: could not coalesce error (error={ "code": -32000, "message": "missing trie node fbc81b7cf76ec579a74fea7d01c93f89e2c5bc3689732697682144c045756594 (path ) state 0xfbc81b7cf76ec579a74fea7d01c93f89e2c5bc3689732697682144c045756594 is not available, not found" }, payload={ "id": 3, "jsonrpc": "2.0", "method": "eth_getProof", "params": [ "0xeaa455e4291742ec362bc21a8c46e5f2b5ed4701", [  ], "0x4c4b40" ] }, code=UNKNOWN_ERROR, version=6.10.0)
    at makeError (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/utils/errors.ts:694:21)
    at JsonRpcProvider.getRpcError (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1049:25)
    at <anonymous> (/home/bear/coding/airdrop-space/axiom/axiom-quickstart/node_modules/.pnpm/ethers@6.10.0/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'UNKNOWN_ERROR',
  error: {
    code: -32000,
    message: 'missing trie node fbc81b7cf76ec579a74fea7d01c93f89e2c5bc3689732697682144c045756594 (path ) state 0xfbc81b7cf76ec579a74fea7d01c93f89e2c5bc3689732697682144c045756594 is not available, not found'
  },
  payload: {
    method: 'eth_getProof',
    params: [ '0xeaa455e4291742ec362bc21a8c46e5f2b5ed4701', [], '0x4c4b40' ],
    id: 3,
    jsonrpc: '2.0'
  },
  shortMessage: 'could not coalesce error'
}

Node.js v21.4.0
```

I noticed that it could be the rpc provider at the first try, but switching to others also reports different errors. Perhaps someone here can help me out.

**Comment by ytham** [comment]
For the `forge test` error, it looks like the submodule in lib/axiom-std is not, for whatever reason, calling npm install (this should automatically happen with `forge test`). Try resetting the submodule to a good state and trying again. From the root of the quickstart repo:
1. foundryup
2. git submodule deinit -f .
3. git submodule update --init
4. git submodule update --remote --recursive
5. forge test -vvv

For the `failed to send onchain query` error. Either of these two solutions should work:
1. Use a different RPC provider (you can use the free accounts for Alchemy, Quicknode, Tenderly, etc) - the free public RPC endpoints will not compute/store the eth_getProof data for older blocks
2. Update the blockNumber values in both `app/axiom/data/inputs.json` as well as `defaultInputs` in `app/axiom/average.circuit.ts` to be more recent (the first error says within 100000 blocks of the most recent block)
